(async()=>{
 const report=document.createElement('pre');report.id='v52Checks';report.style='position:fixed;bottom:0;left:0;max-height:35vh;overflow:auto;z-index:99999;background:#fff;color:#111;padding:8px;font:11px monospace';document.body.append(report);
 const results=[],ok=(value,label)=>{if(!value)throw Error(label);results.push('PASS '+label);report.textContent=results.join('\n');},sleep=ms=>new Promise(r=>setTimeout(r,ms));
 try{
  ok($('ocrProvider').value==='paddle-v5','Paddle default');ok([...$('ocrProvider').options].map(o=>o.value).join(',')===(typeof PDFVision==='undefined'?'paddle-v5,tesseract':'paddle-v5,tesseract,vision'),'Ordered model choices / no standalone cloud');
  const doc=await PDFDocument.create(),p=doc.addPage([400,600]);p.drawText('SECRET-123456',{x:35,y:490,size:22});p.drawText('PUBLIC FOOTER',{x:35,y:40,size:15});
  const field=doc.getForm().createTextField('private-account');field.setText('ACCOUNT-998877');field.addToPage(p,{x:35,y:340,width:290,height:50});doc.setAuthor('PRIVATE-AUTHOR');await doc.attach(new TextEncoder().encode('PRIVATE-ATTACHMENT'),'account.txt');
  const page2=doc.addPage([400,600]);page2.drawText('SECOND PAGE',{x:35,y:500});
  const outline=doc.context.obj({Type:'Outlines'}),outlineRef=doc.context.register(outline),item=doc.context.obj({Title:P.PDFString.of('Second'),Parent:outlineRef,Dest:[page2.ref,'Fit']});const itemRef=doc.context.register(item);outline.set(P.PDFName.of('First'),itemRef);outline.set(P.PDFName.of('Last'),itemRef);outline.set(P.PDFName.of('Count'),P.PDFNumber.of(1));doc.catalog.set(P.PDFName.of('Outlines'),outlineRef);
  await loadFiles([new File([await doc.save()], 'qa-contract.pdf',{type:'application/pdf'})]);await sleep(200);
  const first=pages[0];pages.reverse();render();const reordered=await buildEditedDocument();ok(reordered.getForm().getTextField('private-account').getText()==='ACCOUNT-998877','Reorder retains canonical form value');ok(reordered.catalog.has(P.PDFName.of('Outlines')),'Reorder retains bookmarks');const reopened=await PDFDocument.load(await reordered.save());ok(reopened.getForm().getTextField('private-account').getText()==='ACCOUNT-998877','Reopened form value survives serialization');const tree=reopened.catalog.lookup(P.PDFName.of('Outlines')),dest=tree.lookup(P.PDFName.of('First')).lookup(P.PDFName.of('Dest'));ok(String(dest.get(0))===String(reopened.getPage(0).ref),'Bookmark destination follows reordered page');pages.reverse();render();
  first.annots=[{id:'qa-mask',shape:'redaction',nx:.05,ny:.05,nw:.9,nh:.65,fill:'#000000',stroke:'none',opacity:1,lineWidth:0}];
  const baseline=await buildEditedDocument(),output=await finalizePrivateExport(baseline,pages),bytes=await output.save();
  const clean=await PDFDocument.load(bytes),inspection=PDFDocumentIntegrity.inspect(clean);ok(!inspection.forms&&!inspection.attachments&&!inspection.actions&&!inspection.signatures,'Private PDF removes forms / attachments / actions');ok(clean.getAuthor()!=='PRIVATE-AUTHOR','Source author removed');
  const t=pdfjsLib.getDocument({data:bytes.slice(),...DOC_OPTS}),pdf=await t.promise;ok(pdf.numPages===2,'Private export keeps both pages');
  let extracted='';for(let n=1;n<=pdf.numPages;n++)extracted+=(await(await pdf.getPage(n)).getTextContent()).items.map(i=>i.str).join('');ok(!extracted.includes('SECRET')&&!extracted.includes('ACCOUNT'),'Secret text absent from extractable PDF text');
  const renderPage=await pdf.getPage(1),canvas=document.createElement('canvas'),vp=renderPage.getViewport({scale:1});canvas.width=vp.width;canvas.height=vp.height;await renderPage.render({canvasContext:canvas.getContext('2d'),viewport:vp}).promise;
  const pixel=(x,y)=>canvas.getContext('2d').getImageData(x,y,1,1).data;ok(pixel(50,100)[0]<20&&pixel(50,240)[0]<20,'Mask covers original text AND form appearance');ok(pixel(10,550)[0]>240,'Unmasked page background preserved');
  const visible=document.createElement('canvas');visible.id='qaPrivateResult';visible.width=canvas.width;visible.height=canvas.height;visible.getContext('2d').drawImage(canvas,0,0);visible.style='position:fixed;right:10px;bottom:10px;width:200px;z-index:99998;border:1px solid #aaa';document.body.append(visible);await t.destroy();
  await setProMode('pro');$('proOptimize').checked=false;$('proDeskew').checked=false;refreshProControls();
  const cancelled=createProResult({reveal:false});for(let n=0;n<100&&!$('documentCheckDialog').open;n++)await sleep(20);
  ok($('documentCheckDialog').open&&!$('documentCheckAccept').checked&&$('documentCheckContinue').disabled,'Private export requires explicit loss-of-features acknowledgment');ok(await confirmDocumentExport()===false,'Repeated save cannot create parallel confirmations');$('documentCheckCancel').click();ok(!await cancelled,'Cancelling preflight stops export');
  const pending=createProResult({reveal:false});for(let n=0;n<100&&!$('documentCheckDialog').open;n++)await sleep(20);$('documentCheckAccept').checked=true;$('documentCheckAccept').dispatchEvent(new Event('change'));$('documentCheckContinue').click();const saved=await pending;ok(!!saved?.bytes&&saved.hasPageEffects,'Pro export publishes the masked output');ok($('proReport').textContent.includes('개인정보 마스킹 적용')&&!$('proReport').textContent.includes('OCR을 추가'),'Privacy report does not claim retained searchable OCR');
  const privateTask=pdfjsLib.getDocument({data:saved.bytes.slice(),...DOC_OPTS});const privatePdf=await privateTask.promise;ok((await(await privatePdf.getPage(1)).getTextContent()).items.length===0,'Pro download contains no original hidden text');await privateTask.destroy();
  const rotationDoc=await PDFDocument.create();for(const angle of [90,180,270]){const p=rotationDoc.addPage([400,600]);p.setCropBox(20,30,340,510);p.setRotation(P.degrees(angle));p.node.set(P.PDFName.of('UserUnit'),P.PDFNumber.of(2));p.drawText('ROTATED SECRET',{x:40,y:400,size:20});}
  const rotationBytes=await rotationDoc.save(),rotationTask=pdfjsLib.getDocument({data:rotationBytes.slice(),...DOC_OPTS}),rotationPdf=await rotationTask.promise,rotationId='qa-rotation-source';docs.set(rotationId,{libBytes:rotationBytes,pdfjsDoc:rotationPdf,count:3});
  try{const rotationPages=[0,1,2].map(srcIndex=>({docId:rotationId,srcIndex,rotation:0,annots:[{shape:'redaction',nx:.1,ny:.15,nw:.45,nh:.2}]}));const burned=await finalizePrivateExport(await buildEditedDocument(rotationPages),rotationPages),rt=pdfjsLib.getDocument({data:await burned.save(),...DOC_OPTS}),rp=await rt.promise;
   try{for(let n=1;n<=3;n++){const p=await rp.getPage(n),vp=p.getViewport({scale:.5}),c=document.createElement('canvas');c.width=Math.ceil(vp.width);c.height=Math.ceil(vp.height);await p.render({canvasContext:c.getContext('2d'),viewport:vp}).promise;ok(c.getContext('2d').getImageData(Math.floor(c.width*.3),Math.floor(c.height*.25),1,1).data[0]<20,'Mask geometry survives '+[90,180,270][n-1]+' degree rotation / crop / UserUnit');c.width=c.height=0;}}finally{await rt.destroy();}
  }finally{docs.delete(rotationId);await rotationTask.destroy();}
  first.annots=[];proInvalidate();await showPreview(first);$('ocrSection').open=true;$('privacySection').open=true;syncCounts();
  ok(!document.querySelector('#visionUnlockDialog'),'Hidden password gate removed');
  const help=document.querySelector('.help-dot');ok(!!help,'Contextual help buttons exist');help.dispatchEvent(new PointerEvent('pointerenter',{pointerType:'mouse'}));ok(!$('contextHelp').hidden,'Desktop hover opens help');help.dispatchEvent(new PointerEvent('pointerleave'));ok($('contextHelp').hidden,'Hover exit closes help');
  help.dispatchEvent(new PointerEvent('pointerdown',{pointerType:'touch',clientX:20,clientY:20}));await sleep(400);ok(!$('contextHelp').hidden,'Touch hold opens help');help.dispatchEvent(new PointerEvent('pointerup',{pointerType:'touch'}));ok($('contextHelp').hidden,'Touch release closes help');
  const large=await PDFDocument.create();for(let n=0;n<80;n++)large.addPage([400,600]);await loadFiles([new File([await large.save()],'qa-many-pages.pdf',{type:'application/pdf'})]);await sleep(800);ok(pages.filter(p=>p.canvas).length<=30,'82-page document keeps bounded raster thumbnails');
  report.textContent=results.join('\n')+'\nALL PASSED';document.body.dataset.v52Result='passed';
 }catch(e){report.textContent=results.join('\n')+'\nFAIL '+e.stack;document.body.dataset.v52Result='failed';console.error(e);}
})();
